In [2]:
# 1.Create 1D Numpy Array

import numpy as np

temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [3]:
#2.Inspection and Properties

print('Shape:',temperatures_w1.shape)
print('Data Type:',temperatures_w1.dtype)
print('Number of Elements:',temperatures_w1.size)

temperatures_w1.shape

Shape: (7,)
Data Type: float64
Number of Elements: 7

(7,)

In [4]:
# 3.Array operations

fahrenheit = (temperatures_w1 * 9/5) + 32
print(fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [5]:
# find max,min and mean temperatures

print(np.max(temperatures_w1))
print(np.min(temperatures_w1))
print(round(np.mean(temperatures_w1),2))

26.1
20.8
23.54

In [6]:
#4. Array slicing and indexing

temperatures_w1[:3]

array([22.5, 25.3, 20.8])

In [7]:
temperatures_w1[-2:]

array([24.8, 21.9])

In [8]:
temperatures_w1[2:5]

array([20.8, 23.4, 26.1])

In [9]:
# 5.2D array

temperatures_inweeks=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                             [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures_inweeks)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [10]:
# Inspect and slice the 2D array

print('Shape:',temperatures_inweeks.shape)
print('Data Type:',temperatures_inweeks.dtype)
print('Total no:of elements:',temperatures_inweeks.size)

Shape: (2, 7)
Data Type: float64
Total no:of elements: 14

In [11]:
# Extract each week 

print(temperatures_inweeks[0])
print(temperatures_inweeks[1])

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[19.2 22.5 21.3 24.  23.5 22.8 20.1]

In [12]:
# Extract temperatures for weeks and weekends 

print(temperatures_inweeks[:,-2:])

[[24.8 21.9]
 [22.8 20.1]]

Panda Series

In [13]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in C:\Users\matus\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\matus\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\matus\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\matus\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\matus\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [14]:
import pandas as pd

In [15]:
# 1.creating Panda Series

Marks=pd.Series([95, 92, 89, 85, 80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
Marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [16]:
# 2.Indexing and Slicing

Marks.iloc[0]

np.int64(95)

In [17]:
Marks.loc[['Rank1','Rank2','Rank3']]

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [18]:
Marks.iloc[2]

np.int64(89)

In [19]:
Marks[Marks>90]

Rank1    95
Rank2    92
dtype: int64

In [20]:
# 3.Manipulating Series
# Modify

Marks.loc["Rank1"]=100
Marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [21]:
# removal

Marks=Marks.drop('Rank5')

In [22]:
Marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [23]:
# Calculate CGPA
cgpa = Marks / 10

print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

Pandas DataFrame

In [59]:
# 1.Creating Pandas Data Frame

transactions=pd.DataFrame({'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],
'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [58]:
#2. Data Exploration

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [57]:
print(transactions.info())

<class 'pandas.DataFrame'>
Index: 9 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    9 non-null      int64
 1   ProductCategory  9 non-null      str
 2   Region           9 non-null      str
 3   Amount           9 non-null      int64
dtypes: int64(2), str(2)
memory usage: 491.0 bytes
None

In [56]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [55]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [54]:
print(transactions.shape)

(9, 4)

In [53]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [52]:
print(transactions.dtypes)

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [43]:
# 2.2

print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     165
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
9     Electronics     400

In [51]:
# 2.3

print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     165
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
9     Electronics  North     400

In [50]:
# 2.4

print(transactions[(transactions['Region']=='North') & (transactions['Amount']>200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [49]:
# 2.5

print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      2
Name: count, dtype: int64

In [48]:
# 2.6

print(transactions['Region'].unique())

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [47]:
# 2.7

print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    165.0
West     190.0
Name: Amount, dtype: float64

In [60]:
# Manipulating the dataframe

transactions.loc[transactions['TransactionID']==102,'Amount']= 165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [39]:
# Add a new column

transactions['Discount'] = transactions['Amount'] * 0.10

transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [40]:
# Remove 

transactions=transactions[transactions['TransactionID']!=109]
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [41]:
# Deletion

transactions=transactions.drop('Discount',axis=1)

In [42]:
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400